### PR TITLE
OAuth2 support

### PR DESCRIPTION
**Pull request by StijnCaerts**
## Related issues and pull requests

- Related to discussion #143 

## Description
Add support for OAuth2 token based authorization in asset downloads.
Right now, configuration is handled via environment variables. This is subject to change and just to show the implementation of the client.

Open for comments and improvements.

## Checklist

- [x] Add tests
- [x] Add docs
- [x] Update CHANGELOG

### CODE REVIEW

**Review by gadomski — CHANGES_REQUESTED** [review]
Some initial feedback:
- I'd like to see a the `oath2_grant` and friends as part of the `Config`, with a fallback to environment variables. I've found over the years that environment-only variables can be a bit fragile.
- We'll need to document all the variables used.
- We'll need tests, even if they're behind the `--network-access` gate

Thanks for the contribution!

**Comment by StijnCaerts** [comment]
I moved all configuration options to the `Config`class and added documentation in the docstrings.

For the tests, I added some basic tests for the configuration of the OAuth2 grants in the HTTP client. 
I'm not sure how to approach tests for actual downloads, because the authentication methods either require an interactive user action (device code, authorization code) or require the credentials in the code (password, client credentials).

**Comment by StijnCaerts** [comment]
All CI checks are green now. Would you like any more changes or improvements to this PR?

**Review by gadomski — APPROVED** [review]

**Comment by gadomski** [comment]
Awesome, thanks for the contribution! Looks good to me — I'll release a new version after merging.

**Pull request merged**
